apiVersion: v1
kind: Service
metadata:
    name: "aoai-2827"
    labels:
        app: "aoai-2827"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "aoai-2827"